import { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google"
import "./globals.css";
import { Icon } from "@iconify/react/dist/iconify.js";
const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Specify weights as needed
});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      <div className="bg-[#4C4C53] flex items-center justify-center py-[8px]">
        <div className="text-white mr-[10px] text-[16px]">
          Free shipping on orders over $99
        </div>
        <Icon icon="material-symbols-light:delivery-truck-speed" width="28" height="28" className="text-white" />
      </div>
        <div className="bg-pallete-orange flex items-center justify-center py-[8px] h-[50px]"></div>
        {children}
      </body>
    </html>
  );
}
